services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /data/datadb
  frontend:
    build: 
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "5173:5173"